testing image

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -98,12 +98,13 @@ jobs:
           ECR_REPOSITORY: ${{ env.ecr_repository }}
           IMAGE_TAG: '${{ inputs.branch }}-${{inputs.github_sha}}'
         run: |
-          DOCKER_INFO="$(docker inspect $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG 2>&1)"
-          if [ $? -eq 0 ]; then
-            echo "::set-output name=image-info::${DOCKER_INFO}"
-          else
-            echo "::error::Failed to query Docker image: ${DOCKER_INFO}"
-          fi
+          docker inspect $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+          # DOCKER_INFO="$(docker inspect $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG 2>&1)"
+          # if [ $? -eq 0 ]; then
+          #   echo "::set-output name=image-info::${DOCKER_INFO}"
+          # else
+          #   echo "::error::Failed to query Docker image: ${DOCKER_INFO}"
+          # fi
 
       - name: Build, tag, and push image to Amazon ECR
         id: build-image
@@ -111,7 +112,7 @@ jobs:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
           ECR_REPOSITORY: ${{ env.ecr_repository }}
           IMAGE_TAG: '${{ inputs.branch }}-${{inputs.github_sha}}'
-        if: steps.check_docker_image.outputs.image-info != ''
+        # if: steps.check_docker_image.outputs.image-info != ''
         run: |
           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
             --build-arg REPOSITORY=${{ github.repository }} \
