testing image

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -73,16 +73,21 @@ jobs:
         run: |
           IMAGE_META="$( aws ecr describe-images --repository-name=${{env.service_name}}-${{env.service_version}} --image-ids=imageTag=develop-215fd2d2b0921959c20eb4354ca57712906c99b4 --query 'images[0]' 2>&1 )";
           if [ $? -eq 0 ]; then
-              echo "Images found in repository: ${{env.service_name}}-${{env.service_version}}";
-              IMAGE_TAG=$(echo "$IMAGE_META" | jq '.imageDetails[0].imageTags[0]' -r);
-              echo $IMAGE_TAG;
+            if [ -n "$IMAGE_META" ]; then
+              echo "Images found in repository: ${{ env.service_name }}-${{ env.service_version }}"
+              IMAGE_TAG=$(echo "$IMAGE_META" | jq -r '.imageTags[0]')
+              echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
+            else
+              echo "No images found in repository: ${{ env.service_name }}-${{ env.service_version }}"
+            fi
           else
-              if [[ $IMAGE_META == *"ImageNotFoundException"* ]]; then
-                  echo "No images found in repository:  ${{env.service_name}}-${{env.service_version}}";
-              else
-                  echo "Error: $IMAGE_META";
-              fi;
-          fi;
+            if [[ $IMAGE_META == *"ImageNotFoundException"* ]]; then
+              echo "No images found in repository: ${{ env.service_name }}-${{ env.service_version }}"
+            else
+              echo "Error: $IMAGE_META"
+              exit 1
+            fi
+          fi
           echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
 
       - name: Build, tag, and push image to Amazon ECR
