test ecr

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -72,23 +72,24 @@ jobs:
       - name: Check the image exists in ECR
         id: ecr_image_exists
         run: |
-          IMAGE_META=$( aws ecr describe-images --repository-name=${{ env.service_name }}-${{ env.service_version }} --image-ids=imageTag=${{ inputs.branch }}-${{ inputs.github_sha }} 2>&1 )
-
-          if [ $? -eq 0 ]; then
-              # Command was successful, process the output
-              echo "Images found in repository: ${{ env.service_name }}-${{ env.service_version }}"
-              echo "$IMAGE_META"
-              IMAGE_TAG=$( echo "$IMAGE_META" | jq '.imageDetails[0].imageTags[0]' -r )
-          else
-              # Check if the error is ImageNotFoundException
-              if [[ "$IMAGE_META" == *"ImageNotFoundException"* ]]; then
-                  echo "No images found in repository:  ${{ env.service_name }}-${{ env.service_version }}"
-              else
-                  # Some other error occurred
-                  echo "Error: $IMAGE_META"
-              fi
-          fi
-          echo "image_tag=$IMAGE_TAG"
+          IMAGE_META=$( aws ecr describe-images --repository-name=${{env.service_name}}-${{env.service_version}} --image-ids=imageTag=${{inputs.branch}}-${{inputs.github_sha}} 2>&1 )
+          echo $IMAGE_META
+          
+# if [ $? -eq 0 ]; then
+#     # Command was successful, process the output
+#     echo "Images found in repository: ${{env.service_name}}-${{env.service_version}}"
+#     echo "$IMAGE_META"
+#     IMAGE_TAG="$( echo ${IMAGE_META} | jq '.imageDetails[0].imageTags[0]' -r )"
+# else
+#     # Check if the error is ImageNotFoundException
+#     if [[ "$IMAGE_META" == *"ImageNotFoundException"* ]]; then
+#         echo "No images found in repository:  ${{env.service_name}}-${{env.service_version}}"
+#     else
+#         # Some other error occurred
+#         echo "Error: $IMAGE_META"
+#     fi
+# fi
+# echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
       
       - name: Build, tag, and push image to Amazon ECR
         id: build-image
