testing image

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -71,26 +71,27 @@ jobs:
       - name: Check the image exists in ECR
         id: ecr_image_exists
         run: |
-          set -e
           echo "Start calling ecr"
-          IMAGE_META="$( aws ecr describe-images --repository-name=${{env.service_name}}-${{env.service_version}} --image-ids=imageTag=${{inputs.branch}}-${{inputs.github_sha}} --query 'images[0]' 2>&1 )";
-          echo "End calling ecr"
-          if [[ $? -eq 0 ]]; then
-            echo "Images found in repository: ${{ env.service_name }}-${{ env.service_version }}"
-            if [[ -n $IMAGE_META ]]; then
+          # Run the command and redirect the output to a file
+          aws ecr describe-images --repository-name=${{env.service_name}}-${{env.service_version}} --image-ids=imageTag=${{inputs.branch}}-${{inputs.github_sha}} --query 'images[0]' 2>&1 > ecr_output.txt
+          # Check if the command was successful
+          if [ $? -eq 0 ]; then
+              echo "End calling ecr"
+              # Command was successful, process the output
+              IMAGE_META=$(<ecr_output.txt)
+              echo "Images found in repository: ${{env.service_name}}-${{env.service_version}}"
               IMAGE_TAG=$(echo "$IMAGE_META" | jq -r '.imageTags[0]')
               echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
-            else
-              echo "No images found in repository: ${{ env.service_name }}-${{ env.service_version }}"
-            fi
           else
-            echo "Image not found"
-            if [[ $IMAGE_META == *"ImageNotFoundException"* ]]; then
-              echo "No images found in repository: ${{ env.service_name }}-${{ env.service_version }}"
-            else
-              echo "Error: $IMAGE_META"
-              exit 1
-            fi
+              # Command failed, check the error message
+              ERROR_MSG=$(<ecr_output.txt)
+              if [[ $ERROR_MSG == *"ImageNotFoundException"* ]]; then
+                  echo "No images found in repository: ${{env.service_name}}-${{env.service_version}}"
+                  exit 0
+              else
+                  echo "Error: $ERROR_MSG"
+                  exit 1
+              fi
           fi
           echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
 
