testing image

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -64,52 +64,68 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}
       
-      - name: Run ECR Fetch Image
-        id: ecr_fetch_image
+      - name: Run AWS ECR command
+        id: describe-images
         run: |
-          result=$(aws ecr describe-images --repository-name=odoo-17.0 --image-ids=imageTag=develop-494853f5e336ae7310d267ba546e13d1a17abc2f 2>&1)
-          echo "ecr_result=$result" >> "$GITHUB_OUTPUT"
-
-      - name: Check the image exists in ECR
-        id: ecr_image_exists
+          IMAGE_META=$(aws ecr describe-images --repository-name=odoo-17.0 --image-ids=imageTag=develop-494853f5e336ae7310d267ba546e13d1a17abc2f 2>&1)
+          if [ $? -eq 0 ]; then
+            echo "Command was successful"
+            echo "IMAGE_META=$IMAGE_META" >> $GITHUB_ENV
+          else
+            echo "Error: $IMAGE_META"
+            echo "::error::Failed to describe images"
+          fi
+  
+      - name: Use the output if successful
+        if: ${{ steps.describe-images.outputs.IMAGE_META }}
         run: |
-          echo ${{steps.ecr_fetch_image.outputs.ecr_result}}
+          echo "IMAGE_META: ${{ steps.describe-images.outputs.IMAGE_META }}"
+  
+      - name: Handle error if failed
+        if: ${{ failure() }}
+        run: |
+          echo "An error occurred"
 
-          # IMAGE_META="$( aws ecr describe-images --repository-name=${{env.service_name}}-${{env.service_version}} --image-ids=imageTag=${{inputs.branch}}-${{inputs.github_sha}} 2>&1 )"; \
-          # if [ $? -eq 0 ]; then \
-          #     # Command was successful, process the output \
-          #     echo "Images found in repository: ${{env.service_name}}-${{env.service_version}}"; \
-          #     IMAGE_TAG=$(echo "$IMAGE_META" | jq '.imageDetails[0].imageTags[0]' -r); \
-          #     echo $IMAGE_TAG; \
-          # else \
-          #     # Check if the error is ImageNotFoundException \
-          #     if [[ $IMAGE_META == *"ImageNotFoundException"* ]]; then \
-          #         echo "No images found in repository:  ${{env.service_name}}-${{env.service_version}}"; \
-          #     else \
-          #         # Some other error occurred \
-          #         echo "Error: $IMAGE_META"; \
-          #     fi; \
-          # fi; \
-          # echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
+      # - name: Check the image exists in ECR
+      #   id: ecr_image_exists
+      #   run: |
+      #     echo ${{steps.ecr_fetch_image.outputs.ecr_result}}
+
+      #     # IMAGE_META="$( aws ecr describe-images --repository-name=${{env.service_name}}-${{env.service_version}} --image-ids=imageTag=${{inputs.branch}}-${{inputs.github_sha}} 2>&1 )"; \
+      #     # if [ $? -eq 0 ]; then \
+      #     #     # Command was successful, process the output \
+      #     #     echo "Images found in repository: ${{env.service_name}}-${{env.service_version}}"; \
+      #     #     IMAGE_TAG=$(echo "$IMAGE_META" | jq '.imageDetails[0].imageTags[0]' -r); \
+      #     #     echo $IMAGE_TAG; \
+      #     # else \
+      #     #     # Check if the error is ImageNotFoundException \
+      #     #     if [[ $IMAGE_META == *"ImageNotFoundException"* ]]; then \
+      #     #         echo "No images found in repository:  ${{env.service_name}}-${{env.service_version}}"; \
+      #     #     else \
+      #     #         # Some other error occurred \
+      #     #         echo "Error: $IMAGE_META"; \
+      #     #     fi; \
+      #     # fi; \
+      #     # echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
       
           
-      - name: Login to Amazon ECR
-        id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v1
+      # - name: Login to Amazon ECR
+      #   id: login-ecr
+      #   uses: aws-actions/amazon-ecr-login@v1
 
-      - name: Build, tag, and push image to Amazon ECR
-        id: build-image
-        env:
-          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          ECR_REPOSITORY: ${{ env.ecr_repository }}
-          IMAGE_TAG: '${{ inputs.branch }}-${{inputs.github_sha}}'
-        if: ${{ steps.ecr_image_exists.outputs.image_tag != env.ecr_image_tag }}
-        run: |
-          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
-            --build-arg REPOSITORY=${{ github.repository }} \
-            --build-arg ODOO_VERSION=${{env.service_version}} \
-            --build-arg GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}} \
-            --build-arg GITHUB_SHA=${{inputs.github_sha}} \
-            --build-arg ARTIFACT_ID=${{inputs.artifact-id}} .
-          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
-          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
+      # - name: Build, tag, and push image to Amazon ECR
+      #   id: build-image
+      #   env:
+      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+      #     ECR_REPOSITORY: ${{ env.ecr_repository }}
+      #     IMAGE_TAG: '${{ inputs.branch }}-${{inputs.github_sha}}'
+      #   if: ${{ steps.ecr_image_exists.outputs.image_tag != env.ecr_image_tag }}
+      #   run: |
+      #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
+      #       --build-arg REPOSITORY=${{ github.repository }} \
+      #       --build-arg ODOO_VERSION=${{env.service_version}} \
+      #       --build-arg GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}} \
+      #       --build-arg GITHUB_SHA=${{inputs.github_sha}} \
+      #       --build-arg ARTIFACT_ID=${{inputs.artifact-id}} .
+      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+      #     echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
